# Base configs
baseurl: "/abhasan"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Abhasan"
subtitle: ""
author: "Abhasan Inc"
header:
 title: "Abhasan"
 subtitle: ""
footer:
 name: ""
 bio: ""
 github: ""
web_design: ""
social_urls:
  facebook: ""
  twitter: ""
  instagram: "https://www.instagram.com/iamabhasan"
  dribbble: "https://www.dribble.com/dipin_m"
  behance: "https://www.behance.net/dipinm"
  linkedin: ""
  github: ""
